### ISSUE TITLE
invalid link for wpilib documentation in setup instructions in the README file

### ISSUE THREAD

**Issue by vairakkumaarsvs** [ORF-4450/Robot24B#1]
https://github.com/ORF-4450/Robot24B/blame/master/README.md#L11
This is pointing to a documentation link that is no longer valid

**Comment by cole-wilson** [comment]
I had the same issue. Did you try running the `WPILib: Manage Vendor Libraries > Check for Updates (Online)` command? That should resolve the PathPlanner issue.

However, I don't think the RobotLib dependency is ready for development this year yet so that can't be fixed yet as far as I know. Mr. Corn will probably be able to provide a better response.

**Comment by vairakkumaarsvs** [comment]
i think that is the problem. I am doing that now. I will update  the description to README inaccuracy only. WIll submit PR thereafter

**Comment by vairakkumaarsvs** [comment]
![wpilibRequirement](https://github.com/ORF-4450/Robot24B/assets/129967941/4868f6ff-180a-447e-a933-56974ee8ce62)
CTRE-Phoenix requires both v5 and v6. are both required

**Comment by cole-wilson** [comment]
At the moment yes, although I don't believe this repository is ready for active development yet. Mr. Corn is still getting things updated for this year and there are still issues to be resolved, so you won't be able to get it to compile completely until that happens (as far as I know). [Robot23B2](https://github.com/ORF-4450/Robot23B2) is last year's code, and it compiles nicely if you want to try simulating changes.

**Comment by vairakkumaarsvs** [comment]
corn said this one is running in the Robot and asked me to try on this. but to review and run simulator, yeah the other should help

**Comment by vairakkumaarsvs** [comment]
and i can't run 23b2 since I don't have 23 version of the tool

**Comment by cole-wilson** [comment]
Okay, that makes sense. Here is a link to the 2023 download of WPILib if you are interested: https://github.com/wpilibsuite/allwpilib/releases/tag/v2023.4.1

**Comment by vairakkumaarsvs** [comment]
How to pull the ORF Lib and get included in this ?

**Comment by cole-wilson** [comment]
For the 2023 code you should run the manage vendor libraries command I mentioned above.

**Comment by vairakkumaarsvs** [comment]
I did got this message: package Team4450.Lib does not exists

**Comment by Crossle86** [comment]
I have fixed the bad link.
